### ISSUE TITLE
hello world is broken: misaligned instruction access exception

### ISSUE THREAD

**Issue by ccelio** [ucb-bar/riscv-pk#6]
Currently, building riscv-tools and running ``spike pk hello" throws a misaligned instruction access exception.  I'm not sure which tool is responsible for the error, but I believe it's the proxy kernel. 

The hello world:

    echo -e 'int main(void) {return 0; }' > hello.c
    riscv-gcc -o hello hello.c

The output:

    celio@a5:/scratch/celio$spike /home/eecs/celio/install/riscv/riscv-elf/bin/pk hello 
    z  0000000000000000 ra 0000000000000000 sp 0000000000000000 gp 0000000000000000
    tp 0000000000000000 t0 0000000000000000 t1 0000000000000017 t2 0000000000003514
    s0 0000000000000000 s1 000000007f800000 a0 0000000000000000 a1 0000000000000032
    a2 ffffffffffffffff a3 0000000080000000 a4 000000007f800000 a5 00000000000037c0
    a6 0000000000000017 a7 0000000000003514 s2 0000000000000000 s3 0000000000000000
    s4 0000000000000000 s5 0000000000000000 s6 0000000000000000 s7 0000000000000000
    s8 0000000000000000 s9 000000000000d028 sA 0000000000800000 sB 0000000000800000
    t3 00000000ff800000 t4 0000000000000000 t5 000000007f800000 t6 0000000000003f3c
    sr 0000000000000000 pc 00000000ff800000 va 0000000000000000 insn       00000000
    Misaligned instruction access!

It looks like the PC address 0x00000000ff800000 corresponds to the page table address.

**Comment by aswaterman** [comment]
Resolved: see https://github.com/ucb-bar/riscv-tools/commit/44b1beefa520f796491a3d8f555e662bd79503d1
