### ISSUE TITLE
C compiler cannot create executables

### ISSUE THREAD

**Issue by santhoshvlsi** [ucb-bar/riscv-pk#8]
Commamd: CC=riscv64-unknown-elf-gcc ../configure --prefix=INSTALL_PATH/RISCV/riscv64-unknown-elf --host=riscv64-unknown-elf 

checking build system type... x86_64-unknown-linux-gnu
checking host system type... riscv64-unknown-elf
checking for riscv64-unknown-elf-gcc... riscv64-unknown-elf-gcc
checking whether the C compiler works... no
configure: error: in /Downloads/RISCV/Toolchain/riscv-pk/build':
configure: error: C compiler cannot create executables

**Comment by sbeamer** [comment]
This should be handled by the eventual resolution of issue #7. Please reopen this if it is not the case.

**Comment by mysoreanoop** [comment]
Running the following command (as per the README)
`../configure --prefix=$RISCV --host=riscv64-unknown-elf`
throws the following error (which is the same as posted by the OP):
```
checking build system type... x86_64-pc-linux-gnu
checking host system type... riscv64-unknown-elf
checking for riscv64-unknown-elf-gcc... riscv64-unknown-elf-gcc
checking whether the C compiler works... no
configure: error: in `/home/anoop/work/riscv-pk/build':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
I have attached the config.log file that was generated in the build directory
[config.log](https://github.com/riscv/riscv-pk/files/5055854/config.log)

RISCV is set, and riscv-gnu-toolchain installed and appended to the PATH

**Comment by mysoreanoop** [comment]
Sorry, the issue is resolved. 

I think the problem was that instead of riscv64-unknown-elf-gcc, the compilation process invoked riscv64-unknown-linux-gnu-gcc.

**Comment by LakshmiKanth-77** [comment]
iam not able to interpret the solution. please help me

**Comment by PedroLSF** [comment]
I need help too
